### ISSUE TITLE
Calculating AIC, BIC and AICc

### ISSUE THREAD

**Issue by RebeccaSalles** [helske/KFAS#17]
The latest version of the R-package "KFAS" provides a function for calculating the log-likelihood of an SSModel ("logLik.SSmodel"), however the package does not provide straightforward calculation of the Akaike's Information Criteria, namely the AIC, BIC and AICc. This would be a useful update for the package.

Furthermore, the output from "logLik.SSmodel" does not provide the attributes "df" (degrees of freedom), giving the number of (estimated) parameters in the model, nor "nobs", the number of observations used in estimation, as returned by the function "logLik" in the R-package "stats". Such attributes would also be useful for calculating the Akaike's Information Criteria.

In the meantime, I am calculating the AIC, BIC and AICc criteria as in the following example:

```
  nobs <- length(ts)

  model_arima <- SSModel(ts ~ SSMarima(ar=ar.coef,ma=ma.coef,d=d,Q=NA,stationary=FALSE),H=NA)
  model_arima <- fitSSM(model_arima, inits=c(ar.coef,ma.coef,d,rep(0, 2)))$model

  p <- length(ar.coef)
  q <- length(ma.coef)
  npar <- (p+q+1)

  ll <- logLik(model_arima)
  AIC <- -2*ll+2*npar
  BIC <- -2*ll+log(nobs)*npar
  AICc <- AIC + 2*npar*(npar+1)/(nobs-npar-1)
```

Is this approach for calculating Akaike's Information Criteria for an SSModel adequate?

**Comment by helske** [comment]
I don't think your example code works as you intend to. The default behaviour of `fitSSM` can only be used for estimating the unknown values in `Q` and `H`, so in case of ARMA model you need to provide your own model updating function as argument `updatefn` (see for example new example in [logLik.SSModel](https://github.com/helske/KFAS/blob/master/R/logLik.SSModel.R).

The reason there is no `df` attribute in output of `logLik.SSModel` is that in general it is difficult to know what that value should be as the model can have "arbitrary" structure and the logLik-method can't possibly know what values of the system matrices are estimated and what are taken as known. And even manually figuring out the correct value can be tough in some cases (see for example [mixed models case in lme4](https://stat.ethz.ch/pipermail/r-help/2006-May/094765.html)).

Another issues comes from the initialiazation of the states, in case the states correspond to say regression coefficients you should definitely count the number of such states towards `df`, but what about for example if you have montly seasonal component? By definition in for example at Durbin and Koopman 2012, that should be 12 more parameters (11 diffuse states and 1 variance parameter), but surely we should only count the variance parameter in this case?

So instead of trying to guess the number of parameters (`nobs` is straightforward but not that useful without `df`), I have chosen not to return `df` attribute in `logLik`, as automatic use of `AIC` might lead to erroneus results whereas when manually computing it yourself the blame is on you. ;)

For your ARMA model your code looks otherwise fine expect that your `npar` is off by one if you actually estimate `H` as well (i.e. your model is ARMA + additional noise, not regular ARMA model). Also note that if you have missing observations then `nobs` is incorrect as well.

**Comment by RebeccaSalles** [comment]
Dear Dr. Helske,
I trully appreciate your answer to my question. It was indeed very helpful.
I unsderstand now the reason you have opted not to return the `df` attribute in `logLik.SSModel`.
And thank you for bringing my attention to the implementation errors in my example.

According to your response, the example code you have recommended in [logLik.SSModel](https://github.com/helske/KFAS/blob/master/R/logLik.SSModel.R) and your responses to the Issue #5, I have revised my example as follows:
  
```
  nobs <- length(na.omit(ts))
  p <- length(ar.coef)
  q <- length(ma.coef)
  npar <- (p+q+1)

  model <- SSModel(ts ~ SSMarima(ar=ar.coef,ma=ma.coef,d=d), H=0)
  
  likfn <- function(pars, model, estimate=TRUE){
    tmp <- try(SSMarima(ar=artransform(pars[1:p]),
                        ma=artransform(pars[(p+1):(p+q)]),d=d,Q = exp(pars[(p+q+1)])),silent=TRUE)    
    if(!inherits(tmp,"try-error")){
      model["T","arima"] <- tmp$T 
      model["R","arima"] <- tmp$R    
      model["P1","arima"] <- tmp$P1
      model["Q","arima"] <- tmp$Q
      if(estimate){
        -logLik(model)
      } else model
    } else {
      if(estimate){
        1e100
      } else model
    }
  }
  
  inits <- c(ar.coef,ma.coef,log(var(ts)))
  fit <- optim(inits, likfn, model=model, method='BFGS')
  model <- likfn(fit$par,model,FALSE)

  ll <- logLik(model)
  AIC <- -2*ll+2*npar
  BIC <- -2*ll+log(nobs)*npar
  AICc <- AIC + 2*npar*(npar+1)/(nobs-npar-1)
```

Is this revised approach for estimating the ARMA parameters and calculating the Akaike's Information Criteria for an SSModel adequate?

**Comment by helske** [comment]
There is still one small issue for which I don't have definitive answer though (never really though of this before). If you have no differencing i.e. `d=0`, then you have one more parameter due to the automatic inclusion of the intercept term, so `npar = p+q+2'.  If `d>0` then your current code coincides with the standard `arima` function etc in terms of how `npar` is defined. But on the other hand based on DK2012 you should count the non-stationary states (here the states relating to differencing) as an additional parameters, so in that case you would have `npar = p + q + 1 + d`, but I have never actually seen that kind of AIC definition for ARIMA models... But it seems quite non-standard to compare models with different values of `d` so maybe that is irrelevant in practice. This is again related to the fact that it is not always clear how to identify and count the nonstationary states (I removed misleading paragraph about these in my previous answer, where I mixed up few unrelated issues).

**Comment by RebeccaSalles** [comment]
Thank you so much for your response. Your reccomendations have been most appreciated.
Based on your discussion regarding non-stationary states, I have decided to adopt a more standard definition of AIC for ARIMA models. In that case, I've added the condition `if(d==0) npar <- npar+1` to my previous example code, as suggested.
I am grateful for all your very instructive responses.

**Comment by helske** [comment]
In your model you have an intercept and four covariates and you set only the coefficient corresponding to x1 as time-varying. If you wan't all to be time varying you should use `Q=diag(NA,4)` or if you wan't intercept be time-varying as well, you can either use `SSMtrend(1, Q=NA)` for that or incorporate the intercept into time-varying part as `SSModel(test.y$y1 ~ -1 + SSMregression(~x1+x2+x3+x4, data = test.y, Q=diag(NA, 5), remove.intercept = FALSE), H = NA)`

But this does not fix the error you saw, and this is because the collinearity of the covariates, which causes numerical issues in the smoothed covariance matrices. One thing you could try is to use more informative prior variance for the states, i.e. instead of using the default diffuse initialization (P1inf is diagonal and P1=0) you could set for example the prior variance to 1000 (still quite weakly informative): `SSModel(test.y$y1 ~ -1 + SSMregression(~x1+x2+x3+x4, data = test.y, Q=diag(NA, 5), remove.intercept = FALSE, P1 = diag(1000, 5)), H = NA)`

The estimation of the regression coefficients is done automatically by Kalman filter so you can still use `fitSSM` for estimation of Q and H, and the number of parameters is number of states + number of parameters in Q + 1 from H ie. 2*k+1 if k is the number of covariates (assuming all are time-varying).

**Comment by RebeccaSalles** [comment]
Dear Dr. Helske,
Thank you so much for your instructions. I have learned a great deal from them. Your help was very valuable and most appreciated. I believe this issue can be closed now.
