### ISSUE TITLE
Order of columns of bivariate data for Poisson models

### ISSUE THREAD

**Issue by mallerhand** [helske/KFAS#39]
Why do these two chunks give different results? Have I miss-specified?

model <- SSModel(cbind(DriversKilled, VanKilled) ~ SSMtrend(1, Q = matrix(NA,2,2)),
               data = Seatbelts, distribution = rep("poisson",2))
fit <- fitSSM(model, diag(c(-4,-4)), method = "BFGS")
predict(fit$model)

model <- SSModel(cbind(VanKilled, DriversKilled) ~ SSMtrend(1, Q = matrix(NA,2,2)),
               data = Seatbelts, distribution = rep("poisson",2))
fit <- fitSSM(model, diag(c(-4,-4)), method = "BFGS")
predict(fit$model)

**Comment by helske** [comment]
The initial values argument should a vector with length corresponding to the number of unknown parameters, i.e. 3 here (two variances and one covariance parameter). If you check `fit$optim.out` from your two cases you can see that they have converged to different values due to different initial values. If you use say `c(-4,-4,0)` for both you should get identical results.

**Comment by mallerhand** [comment]
thanks, issue resolved.
I had passed a 2x2 matrix to inits instead of a 3-vector, forgetting the off-diagonal is the same one covariance, (not two).

Great stuff!

________________________________
