### ISSUE TITLE
Regression effect for level or slope

### ISSUE THREAD

**Issue by Vera1996** [helske/KFAS#60]
Dear Helske,

is it possible to put the regression effect in the updating equation for the level \mu_t or slope \nu_t?
The regression effect is now based on the observations when I use SSMregression. I want to know if de data that I use for the regression, affect the level or slope. So the growth or the growth of the growth.
Now I have:
model <- SSModel(covid_new[, 1:4] ~ SSMtrend(2, Q = list(diag(NA, 4, 4), diag(NA, 4, 4)),
                                             P1 = diag(100, 8, 8), P1inf = diag(0, 8, 8))
                                             + 
                   SSMregression(list(~lag_1$Germany, 
                                      ~lag_1$Netherlands, 
                                      ~lag_1$Spain, 
                                      ~lag_1$Sweden),
                                 P1 = diag(100, 4, 4), P1inf = diag(0, 4, 4)), 
                                 H = diag(NA, 4, 4))

I hope you can help me!

**Comment by helske** [comment]
You can do it if you define your model using `SSMcustom` components i.e. you define the necessary system matrices manually, and then create corresponding updating function for `fitSSM`. Basically, you have to modify Z and T matrices according to your needs so that the previous state (regression coefficient) affects the new state (level and/or slope) via T.
