### ISSUE TITLE
Exact diffuse intialisation

### ISSUE THREAD

**Issue by AdamElderfield** [helske/KFAS#69]
Hi,

This is question rather than an issue. I want to understand exact diffuse intialisation better, could you please point me to code that handles this for KFAS?

**Comment by helske** [comment]
The codes are in the Fortran files `src/filter1step.f90`, and the actual equations used can be found in the appendix of the KFAS paper at JSS: https://www.jstatsoft.org/article/view/v078i10

**Comment by AdamElderfield** [comment]
Thank you. How does KFAS handle initialization with a mix of stationary and non-stationary states? Say for example, a trend cycle decomposition? Are the steady state values solved for the stationary part?

**Comment by helske** [comment]
Stationary distribution in the case of ARIMA processes is solved within the SSMarima function based on the input, otherwise, an arbitrary combination of diffuse and non-diffuse initialization works by checking the corresponding (diagonal) elements of P and Pinf during the filtering. The handling follows the article above with further details in Durbin & Koopman book (and the corresponding articles by them).
