### ISSUE TITLE
Returning Importance Samples in predict.SSModel

### ISSUE THREAD

**Issue by bking124** [helske/KFAS#72]
When working with non-Gaussian models such as Poisson, I would like to access draws from the forecast distribution.  It seems that such a sample is being drawn in the background by predict.SSModel when nsim is set to a positive number.  However, the function only returns the point predictions and errors.  Is there any way to access those draws?  Would I need a separate call to importanceSSM?

**Comment by bking124** [comment]
Appreciate the response and explanation!  Another predict method that always samples would definitely be useful.

For now, I think I've figured out how to appropriately augment the data so that calling `importanceSSM` will output forecasts, but I'm not 100% sure how to combine the samples appropriately using the weights.  Is it just a matter of multiplying the appropriate matrices from the function output?  Do I need to scale the weights matrix so that it sums to 1 first?

**Comment by helske** [comment]
For computing summary statistics other than ones provided by `predict` you can compute weighted averages of arbitrary functions, see e.g. Section 3 of the [KFAS paper](https://www.jstatsoft.org/article/view/v078i10). If you scale the weights first so that they sum to 1 then the weighted average turns to the weighted sum.

For doing something with individual draws (e.g. visualizations), probably the easiest way is to resample (with replacement) the draws using the importance weights, so you end up with a non-weighted sample which is easier to handle.
